
#include "ZWApplianceRes.hpp"

#include <pgmspace.h>

const char PORTAL_INDEX_PAGE[] PROGMEM =
  "<!DOCTYPE html>"
  "<html>"
  "<body>"
  "<h1>A Fresh Start!</h1>"
  "<hr>"

  "<h2>This is the default index page.</h2>"
  "<p>Once you have created your own index page, you won't see this page again.<br>"
  "But before then, there are some links below to help you to get around.<br>"
  "(The administrative login user name is '" PORTAL_ADMIN_USER "', which is also the default password.)"

  "<ul>"

  "<li>To manage accounts and access control, <a href=\"" PORTAL_AUTH_FILE "\">click here</a>;"
  "<ul><li><em>You are strongly recommended to change the default adminstrator's password!</em></ul>"

  "<li>To change device configuration, <a href=\"" PORTAL_CONFIG_FILE "\">click here</a>;"
  "<ul><li><em>Most configuration changes require a restart to become effective.</em></ul>"

  "<li>To restart this device, <a href=\"" PORTAL_API_HWCTL_DEVRESTART "\">click here</a>;"

  "<li>To perform an over-the-air firmware update, <a href=\"" PORTAL_OTA_FILE "\">click here</a>;"

  "<li>To get a plain view of the whole file system, <a href=\"" PORTAL_FSDAV_ROOT "\">click here</a>;"
  "<ul>"
  "<li><em>The '" PORTAL_DIR "' sub-folder is the effective Web root.</em>"
  "<li><em>Directory index file name is '" PORTAL_INDEX_FILE "'.</em>"
  "<li>You can also mount this location as a WebDAV folder."
  "</ul>"

  "<li style=\"color:red\">Lastly, to erase all your customizations and start over, "
  "<a href=\"" PORTAL_API_HWCTL_DEVRESET "\">click here</a>."
  "<ul><li><em>Be careful, when you click the above link, there is no going back!</em></ul>"

  "</ul>"

  "</body>"
  "</html>";

const char PORTAL_DEVRESET_PAGE[] PROGMEM =
  "<!DOCTYPE html>"
  "<html>"
  "<body>"
  "<h1>Reset in Progress</h1>"
  "<hr>"

  "<h2>This device is being reset...</h2>"
  "<p>All your configurations are erased, and device will reinitialize after restart."

  "<ul>"
  "<li>Wait for about 10 seconds, and <a href=\"" PORTAL_ROOT "\">click here</a>."
  "</ul>"

  "</body>"
  "</html>";

const char PORTAL_DEVRESTART_PAGE[] PROGMEM =
  "<!DOCTYPE html>"
  "<html>"
  "<body>"
  "<h1>Restart in Progress</h1>"
  "<hr>"

  "<h2>This device is being restarted...</h2>"
  "<p>All your configurations are persisted, and device will resume operation after restart."

  "<ul>"
  "<li>Wait for about 10 seconds, and <a href=\"" PORTAL_ROOT "\">click here</a>."
  "</ul>"

  "</body>"
  "</html>";

const char PORTAL_PANIC_PAGE[] PROGMEM =
  "<!DOCTYPE html>"
  "<html>"
  "<body>"
  "<h1>Ooops, something went horribly wrong!</h1>"
  "<hr>"

  "<h2>But don't worry, this device is not dead yet.</h2>"
  "<p>You can still recover by a hard reset, but you will loose all your configurations."

  "<ul>"
  "<li>To do that, you need to authenticate as an administrator."
  "<li>When you are ready, <a href=\"" PORTAL_API_HWCTL_DEVRESET "\">click here</a>."
  "</ul>"

  "</body>"
  "</html>";

const char PORTAL_OTA_PAGE[] PROGMEM =
  "<!DOCTYPE html>"
  "<html>"
  "<head>"
  "<script src=\"" PORTAL_OTARES_MD5JS "\"> </script>"
  "<script src=\"" PORTAL_OTARES_OTACOREJS "\"> </script>"
  "<style>"
  "#ota-msg {"
  "  outline: 1px solid;"
  "  padding: 0.25em;"
  "}"
  "#ota-msg.ready {"
  "  color: grey;"
  "  background: whitesmoke;"
  "}"
  "#ota-msg.notready {"
  "  color: darkgoldenrod;"
  "  background: oldlace;"
  "}"
  "#ota-msg.progress {"
  "  color: cornflowerblue;"
  "  background: aliceblue;"
  "}"
  "#ota-msg.succeed {"
  "  color: mediumseagreen;"
  "  background: mintcream;"
  "}"
  "#ota-msg.fail {"
  "  color: indianred;"
  "  background: lavenderblush;"
  "}"
  "</style>"
  "<script>"
  "function getNotifyBanner(formElem) {"
  "  var msgElem = document.getElementById('ota-msg');"
  "  if (msgElem == null) {"
  "    msgElem = document.createElement('div');"
  "    msgElem.id = 'ota-msg';"
  "    formElem.parentNode.insertBefore(msgElem, formElem);"
  "  }"
  "  return msgElem;"
  "}"
  "var OTAUI = {};"
  "function ota_avail(state, comp, msg) {"
  "  var msgElem = getNotifyBanner(OTAUI['Form']);"
  "  if (state) {"
  "    msgElem.className = 'ready';"
  "    msgElem.innerHTML = 'Ready for upload';"
  "    OTAUI.Submit.disabled = false;"
  "  } else {"
  "    msgElem.className = 'notready';"
  "    msgElem.innerHTML = msg;"
  "    OTAUI.Submit.disabled = true;"
  "  }"
  "}"
  "function ota_select(evt) {"
  "  var uploadSpec = event.srcElement.files;"
  "  if (uploadSpec.length > 0) {"
  "    OTAUI.Core.selectFile(uploadSpec[0]);"
  "  } else {"
  "    OTAUI.Core.selectFile();"
  "  }"
  "}"
  "function ota_upload() {"
  "  OTAUI.Core.uploadDo(function(succ,prog) {"
  "    var msgElem = getNotifyBanner(OTAUI['Form']);"
  "    if (succ === undefined) {"
  "      OTAUI.Abort.disabled = false;"
  "      msgElem.className = 'progress';"
  "      msgElem.innerHTML = 'Upload in progress... ' +"
  "        (prog <= 1? (prog*100).toFixed(1) + '%' : prog);"
  "    } else if (succ) {"
  "      OTAUI.Abort.disabled = true;"
  "      msgElem.className = 'succeed';"
  "      msgElem.innerHTML = 'Upgrade successful! ' +"
  "        'To restart device, <a href=\"" PORTAL_API_HWCTL_DEVRESTART "\">click here</a>.';"
  "    } else {"
  "      OTAUI.Abort.disabled = true;"
  "      msgElem.className = 'fail';"
  "      msgElem.innerHTML = 'Upgrade failed - ' + prog;"
  "    }"
  "  });"
  "}"
  "function ota_abort() {"
  "  OTAUI.Core.uploadAbort();"
  "}"
  "window.onload = function() {"
  "  OTAUI['Form'] = document.getElementById('ota-form');"
  "  OTAUI['Submit'] = document.getElementById('ota-submit');"
  "  OTAUI['Abort'] = document.getElementById('ota-abort');"
  "  OTAUI['Core'] = new OTA('" PORTAL_API_OTA "', ota_avail);"
  "  OTAUI.Abort.onclick = ota_abort;"
  "  OTAUI.Abort.disabled = true;"
  "};"
  "</script>"
  "</head>"
  "<body>"
  "<h1>Firware Update</h1>"
  "<hr>"

  "<h2>This is the default firmware update page.</h2>"
  "<p>You can override this page by creating the '" PORTAL_OTA_FILE "' file in the "
  "<a href=\"" PORTAL_FSDAV PORTAL_DIR "\">'" PORTAL_DIR "' sub-folder</a>."

  "<form id=\"ota-form\" action=\"javascript:void(0)\" onsubmit=\"ota_upload()\">"
  "<p>Please follow the steps below:"
  "<ol>"

  "<li>Select the firmware file: <input id=\"ota-file\" type=\"file\" onchange=\"ota_select(event)\"><br>"
  "<br>"
  "<li>Confirm by click this button: <input id=\"ota-submit\" type=\"submit\" value=\"Perform Update\"><br>"
  "To abort update, click this button: <input id=\"ota-abort\" type=\"button\" value=\"Abort Update\">"
  "</form>"
  "</ul>"
  "</body>"
  "</html>";

